//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Framework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum AnswerType
	{
		Text,
		Boolean,
		MultipleChoice,
		SingleChoice,
		Integer,
		Real,
	}
}
