//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using IdentitySample.Models;

namespace Framework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CustomScore
	{
        [Key, Column(Order = 0)]
        [Required, Display(Name = "Consultant")]
		public virtual string Id
		{
			get;
			set;
		}

	    [Key, Column(Order = 1)]
	    [Required, Display(Name = "Interview")]
	    public virtual int IdInterview
	    {
	        get; set;
        }

        [Key, Column(Order = 2)]
        [Required, Display(Name = "Node")]
        public virtual int? IdNode
		{
			get;
			set;
		}

		public virtual int Value
		{
			get;
			set;
		}

		public virtual string Comment
		{
			get;
			set;
		}

        [ForeignKey("Id")]
        public virtual ApplicationUser ApplicationUsers { get; set; }
        public Node Node { get; set; }
        public Interview.Interview Interview { get; set; }
	}
}

