//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Node
	{
        [Key]
		public virtual int IdNode
		{
			get;
			set;
		}
        [Display(Name = "Node")]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual int Weight
		{
			get;
			set;
		}
        [Display(Name = "Is Root ?")]
		public virtual bool IsRoot
		{
			get;
			set;
		}

		public virtual string Equation
		{
			get;
			set;
		}

        public int IdPerspective { get; set; }
        public Perspective Perspective { get; set; }
        public int? IdParentNode { get; set; }
        [ForeignKey("IdParentNode")]
        public Node ParentNode { get; set; }
        public int? IdQuestionnaire { get; set; }
        [ForeignKey("IdQuestionnaire")]
        public Questionnaire Questionnaire { get; set; }
	}
}

