//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Framework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Perspective
	{
        [Key]
		public virtual int IdPerspective
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}
        [Display(Name = "Perspective")]
		public virtual string Name
		{
			get;
			set;
		}
        [Display(Name = "Is Default ?")]
		public virtual bool IsDefault
		{
			get;
			set;
		}

		public virtual int Weight
		{
			get;
			set;
		}
        [Required, Display(Name = "Framework")]
        public int? IdFramework { get; set; }

        public Framework Framework { get; set; }

		
	}
}

