//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Framework
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Proposition
	{
        [Key]
		public virtual int IdProposition
		{
			get;
			set;
		}

		public virtual int Value
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}
        [Required, Display(Name = "Question")]
        public int? IdQuestion { get; set; }

        public Question Question { get; set; }

	}
}

