//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Framework
{
	using Interview;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Questionnaire
	{
        [Key]
		public virtual int IdQuestionnaire
		{
			get;
			set;
		}
        [Display(Name = "Is Draft ?")]
		public virtual bool IsDraft
		{
			get;
			set;
		}
        [Display(Name = "Questionnaire")]
        public virtual string Name
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

		public virtual Language Language
		{
			get;
			set;
		}
        [Display(Name = "Auto Scoring ?")]
	    public virtual bool AutoScore
	    {
	        get; set;
	    }

        [Required, Display(Name = "Framework")]
        public int IdFramework { get; set; }
        public Framework Framework { get; set; }
        public ICollection<Node> Nodes { get; set; } 
        public ICollection<Question> Questions { get; set; }
	}
}

