//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Framework
{
	using Interview;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Question
	{
        [Key]
		public virtual int IdQuestion
		{
			get;
			set;
		}
        [Display(Name = "QID")]
	    public virtual string Ident { get; set; }
        [Display(Name = "Question")]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}
        [Display(Name = "Is Factor ?")]
		public virtual bool IsFactor
		{
			get;
			set;
		}
        [Display(Name = "Is Relevant ?")]
		public virtual bool IsRelevant
		{
			get;
			set;
		}

        public virtual string PossibleAnswer { get; set; }

		public virtual AnswerType AnswerType
		{
			get;
			set;
		}
        [Required, Display(Name = "Role")]
        public int IdRole { get; set; }
        [Required, Display(Name = "Node")]
        public int? IdNode { get; set; }
        [Required, Display(Name = "Questionnaire")]
        public int IdQuestionnaire { get; set; }

        public Role Role { get; set; }

        public Node Node { get; set; }
        public Questionnaire Questionnaire { get; set; }
	}
}

