// <auto-generated />
namespace Octant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class required1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505291355225_required1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
