// <auto-generated />
namespace Octant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class candiroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candiroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201508181426393_candiroles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
