//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Framework;

namespace Interview
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Answer
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int IdAnswer
		{
			get;
			set;
		}

		public virtual int Value
		{
			get;
			set;
		}

        public virtual string IntervieweeAnswer { get; set; }

		public virtual string Comment
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

        [Display(Name = "Consultant Comment")]
		public virtual string ConsultantComment
		{
			get;
			set;
		}

        [Required, Display(Name = "Interview")]
        public int? IdInterview { get; set; }
        public Interview Interview { get; set; }
        [Required, Display(Name = "Question")]
        public int? IdQuestion { get; set; }
        public Question Question { get; set; }
	}
}

