//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Octant.Models.Interview;

namespace Interview
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Customer
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int IdCustomer
		{
			get;
			set;
		}
        [Required, Display(Name = "Customer")]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string Comment
		{
			get;
			set;
		}

        public virtual Industry Industry { get; set; }
        [Required, Display(Name = "Industry")]
        public virtual int? IdIndustry { get; set; }
        public virtual Firm Firm { get; set; }
        [Required, Display(Name = "Firm")]
        public virtual int IdFirm { get; set; }
	}
}

