//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Interview
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Group
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int IdGroup
		{
			get;
			set;
		}
        [Required, Display(Name = "Group")]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual string Comment
		{
			get;
			set;
		}

        public int? IdCampaign { get; set; }
        [ForeignKey("IdCampaign")]
        public Campaign Campaign { get; set; }

        //public virtual ICollection<Candidate> Candidates { get; set; }
	}
}

