//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Interview
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Interviewee
	{
        [Key, Column(Order = 0)]
        [Required, Display(Name = "Candidate")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual int? IdCandidate
		{
			get;
			set;
		}

        [Key, Column(Order = 1)]
        [Required, Display(Name = "Interview")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public virtual int? IdInterview
		{
			get;
			set;
		}

        public Interview Interview { get; set; }
        public Candidate Candidate { get; set; }
	}
}

