//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Framework;
using IdentitySample.Models;

namespace Interview
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Interview
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual int IdInterview
		{
			get;
			set;
		}
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public virtual DateTime Date
		{
			get;
			set;
		}
        [Required, Display(Name = "Interview")]
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Comment
		{
			get;
			set;
		}

		public virtual bool Canceled
		{
			get;
			set;
		}

		public virtual bool Suspended
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual int Completion
		{
			get;
			set;
		}
        [DefaultValue(null)]
	    public virtual int? Score
	    {
	        get; set;
	    }

        [DefaultValue(false)]
        public virtual bool Deleted { get; set; }

        [Required, Display(Name = "Consultant")]
        public string Id { get; set; }
        [ForeignKey("Id")]
        public virtual ApplicationUser ApplicationUsers { get; set; }
        [Required, Display(Name = "Campaign")]
        public int? IdCampaign { get; set; }
        [ForeignKey("IdCampaign")]
        public Campaign Campaign { get; set; }
        public virtual IList<Candidate> Candidates { get; set; }
	}
}

